require 'rake/testtask'

# Create .wing_commander directory for XML output
directory '.wing_commander'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
  t.options = '--ci-reporter'
end

desc 'Run tests with JUnit XML output'
task :test => '.wing_commander' do
  ENV['CI_REPORTS'] = '.wing_commander'
  Rake::Task['test'].invoke
end
