require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

desc 'Run tests with JUnit XML output'
task :test do
  ENV['CI_REPORTS'] = 'test/reports'
  Rake::Task['test'].invoke
end
